### ISSUE TITLE
Doesn't work with httpauth-basic

### ISSUE THREAD

**Issue by pstn** [accidentalrebel/emacs-dokuwiki#3]
My dokuwiki is not doing it's own auth, but uses the httpauth plugin.
Unfortunately that doesn't seem to be supported here.
Would you consider supporting this setup? I really like to have my xmlrpc behind httpauth.

**Comment by accidentalrebel** [comment]
Hi there! Can you provide a link to the plugin that you mention?

I've yet to look into auth plugins. Will see if it is something I can be able to tackle. :)

**Comment by pstn** [comment]
Hello!

It is the [HTTP Authentication Plugin](https://www.dokuwiki.org/plugin:authhttp) that uses the webserver to do [Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) and just uses the username provided (at least in my setup).

I use this method because it doesn't expose any part of the website, to an unauthenticated user.
